// <auto-generated />
using System;
using Eventor.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Eventor.Migrations
{
    [DbContext(typeof(EventorDBContext))]
    [Migration("20250328192113_ImproveRelationships")]
    partial class ImproveRelationships
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Eventor.Database.Models.DayDBModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("day_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("uuid")
                        .HasColumnName("menu_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<double>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_number");

                    b.HasKey("Id");

                    b.ToTable("days");
                });

            modelBuilder.Entity("Eventor.Database.Models.EventDBModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int>("DaysCount")
                        .HasColumnType("integer")
                        .HasColumnName("days_count");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<double>("Percent")
                        .HasColumnType("numeric")
                        .HasColumnName("percent");

                    b.Property<int>("PersonCount")
                        .HasColumnType("integer")
                        .HasColumnName("person_count");

                    b.Property<double>("Rating")
                        .HasColumnType("numeric")
                        .HasColumnName("rating");

                    b.HasKey("Id");

                    b.ToTable("events");
                });

            modelBuilder.Entity("Eventor.Database.Models.EventDayDBModel", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<Guid>("DayId")
                        .HasColumnType("uuid")
                        .HasColumnName("day_id");

                    b.HasKey("EventId", "DayId");

                    b.HasIndex("DayId");

                    b.ToTable("events_days");
                });

            modelBuilder.Entity("Eventor.Database.Models.FeedbackDBModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("feedback_id");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("comment");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<double>("Rating")
                        .HasColumnType("numeric")
                        .HasColumnName("rating");

                    b.HasKey("Id");

                    b.ToTable("feedbacks");
                });

            modelBuilder.Entity("Eventor.Database.Models.ItemDBModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<double>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<int>("Type")
                        .HasColumnType("item_type")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("items");
                });

            modelBuilder.Entity("Eventor.Database.Models.LocationDBModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<double>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("locations");
                });

            modelBuilder.Entity("Eventor.Database.Models.MenuDBModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("menu_id");

                    b.Property<double>("Cost")
                        .HasColumnType("numeric")
                        .HasColumnName("cost");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("menu");
                });

            modelBuilder.Entity("Eventor.Database.Models.MenuItemsDBModel", b =>
                {
                    b.Property<Guid>("MenuId")
                        .HasColumnType("uuid")
                        .HasColumnName("menu_id");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<int>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.HasKey("MenuId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("menu_items");
                });

            modelBuilder.Entity("Eventor.Database.Models.PersonDBModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<bool>("Paid")
                        .HasColumnType("bool")
                        .HasColumnName("paid");

                    b.Property<int>("Type")
                        .HasColumnType("person_type")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("persons");
                });

            modelBuilder.Entity("Eventor.Database.Models.PersonDayDBModel", b =>
                {
                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<Guid>("DayId")
                        .HasColumnType("uuid")
                        .HasColumnName("day_id");

                    b.Property<Guid?>("DayDBModelId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PersonDayDBModelDayId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PersonDayDBModelPersonId")
                        .HasColumnType("uuid");

                    b.HasKey("PersonId", "DayId");

                    b.HasIndex("DayDBModelId");

                    b.HasIndex("PersonDayDBModelPersonId", "PersonDayDBModelDayId");

                    b.ToTable("persons_days");
                });

            modelBuilder.Entity("Eventor.Database.Models.UserDBModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Gender")
                        .HasColumnType("gender")
                        .HasColumnName("gender");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("phone");

                    b.Property<int>("Role")
                        .HasColumnType("role")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Eventor.Database.Models.UserEventDBModel", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.HasKey("UserId", "EventId");

                    b.HasIndex("EventId");

                    b.ToTable("users_events");
                });

            modelBuilder.Entity("Eventor.Database.Models.EventDayDBModel", b =>
                {
                    b.HasOne("Eventor.Database.Models.DayDBModel", "Day")
                        .WithMany("EventDays")
                        .HasForeignKey("DayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eventor.Database.Models.EventDBModel", "Event")
                        .WithMany("EventDays")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Day");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Eventor.Database.Models.MenuItemsDBModel", b =>
                {
                    b.HasOne("Eventor.Database.Models.ItemDBModel", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eventor.Database.Models.MenuDBModel", "Menu")
                        .WithMany("MenuItems")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("Eventor.Database.Models.PersonDayDBModel", b =>
                {
                    b.HasOne("Eventor.Database.Models.DayDBModel", null)
                        .WithMany("PersonDays")
                        .HasForeignKey("DayDBModelId");

                    b.HasOne("Eventor.Database.Models.PersonDBModel", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eventor.Database.Models.PersonDayDBModel", null)
                        .WithMany("PersonDays")
                        .HasForeignKey("PersonDayDBModelPersonId", "PersonDayDBModelDayId");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Eventor.Database.Models.UserEventDBModel", b =>
                {
                    b.HasOne("Eventor.Database.Models.EventDBModel", "Event")
                        .WithMany("UserEvents")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eventor.Database.Models.UserDBModel", "User")
                        .WithMany("UserEvents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Eventor.Database.Models.DayDBModel", b =>
                {
                    b.Navigation("EventDays");

                    b.Navigation("PersonDays");
                });

            modelBuilder.Entity("Eventor.Database.Models.EventDBModel", b =>
                {
                    b.Navigation("EventDays");

                    b.Navigation("UserEvents");
                });

            modelBuilder.Entity("Eventor.Database.Models.MenuDBModel", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("Eventor.Database.Models.PersonDayDBModel", b =>
                {
                    b.Navigation("PersonDays");
                });

            modelBuilder.Entity("Eventor.Database.Models.UserDBModel", b =>
                {
                    b.Navigation("UserEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
